### ISSUE TITLE
Build errors without `vue` and `nuxt3` as externals

### ISSUE THREAD

**Issue by benjamincanac** [nuxt/module-builder#19]
By using `@nuxt/module-builder` v0.1.6, as mentioned in [this comment](https://github.com/nuxt-community/strapi-module/pull/214#discussion_r786960399), I'm reporting all the errors I have without `vue` and `nuxt3` defined in `build.externals`:

```
 WARN  Inlining implicit external nuxt3/dist/app/composables/cookie                                                                                                          
 WARN  Inlining implicit external vue                                                                                                                                        18:22:21
 WARN  Inlining implicit external cookie-es                                                                                                                                  18:22:21
 WARN  Inlining implicit external h3                                                                                                                                         18:22:21
 WARN  Inlining implicit external destr                                                                                                                                      18:22:21
 WARN  Inlining implicit external #app                                                                                                                                       18:22:21

Could not resolve import "#app" in /Users/benjamincanac/Projects/nuxt/strapi-module/node_modules/nuxt3/dist/app/composables/cookie.mjs using imports defined in /Users/benjamincanac/Projects/nuxt/strapi-module/node_modules/nuxt3/package.json.

 WARN  Inlining implicit external #app                                                                                                                                       18:22:21

Could not resolve import "#app" in /Users/benjamincanac/Projects/nuxt/strapi-module/node_modules/nuxt3/dist/app/composables/cookie.mjs using imports defined in /Users/benjamincanac/Projects/nuxt/strapi-module/node_modules/nuxt3/package.json.

 WARN  Inlining implicit external #app                                                                                                                                       18:22:21
 WARN  Inlining implicit external #app                                                                                                                                       18:22:21

'#app' is imported by node_modules/nuxt3/dist/app/composables/cookie.mjs, but could not be resolved – treating it as an external dependency

 WARN  Inlining implicit external @vue/runtime-dom                                                                                                                           18:22:23

node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js(1,1): error TS9005: Declaration emit for this file requires using private name 'VueCustomElement'. An explicit type annotation may unblock declaration emit.
node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js(1,1): error TS9005: Declaration emit for this file requires using private name 'VueCustomElement'. An explicit type annotation may unblock declaration emit.

Error: Failed to compile. Check the logs above.
    at error (file:///Users/benjamincanac/Projects/nuxt/strapi-module/node_modules/rollup/dist/es/shared/rollup.js:10363:30)
    at throwPluginError (file:///Users/benjamincanac/Projects/nuxt/strapi-module/node_modules/rollup/dist/es/shared/rollup.js:21681:12)
    at Object.error (file:///Users/benjamincanac/Projects/nuxt/strapi-module/node_modules/rollup/dist/es/shared/rollup.js:22395:20)
    at Object.error (file:///Users/benjamincanac/Projects/nuxt/strapi-module/node_modules/rollup/dist/es/shared/rollup.js:21858:42)
    at Object.transform (file:///Users/benjamincanac/Projects/nuxt/strapi-module/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1572:26)
    at file:///Users/benjamincanac/Projects/nuxt/strapi-module/node_modules/rollup/dist/es/shared/rollup.js:22640:37 {
  id: '/Users/benjamincanac/Projects/nuxt/strapi-module/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js',
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  plugin: 'dts',
  watchFiles: [
    '/Users/benjamincanac/Projects/nuxt/strapi-module/src/module.ts',
    '/Users/benjamincanac/Projects/nuxt/strapi-module/node_modules/nuxt3/dist/app/composables/cookie.mjs',
    '/Users/benjamincanac/Projects/nuxt/strapi-module/node_modules/cookie-es/dist/index.mjs',
    '/Users/benjamincanac/Projects/nuxt/strapi-module/node_modules/vue/dist/vue.runtime.esm-bundler.js',
    '/Users/benjamincanac/Projects/nuxt/strapi-module/node_modules/h3/dist/index.mjs',
    '/Users/benjamincanac/Projects/nuxt/strapi-module/node_modules/destr/dist/index.mjs',
    '/Users/benjamincanac/Projects/nuxt/strapi-module/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js'
  ]
}
```

**Comment by pi0** [comment]
Can you please try 0.1.7? Also #app being bundled is strange. Will try the branch.

**Comment by benjamincanac** [comment]
@pi0 `v0.1.7` does fix the issue, it was to demonstrate why I added this in the first place
