### ISSUE TITLE
nuxt-module-build error from module starter

### ISSUE THREAD

**Issue by gaetansenn** [nuxt/module-builder#56]
Hello,

i'm facing a problem with the module starter locally.
Command: 
```
npx nuxi init -t module my-module
```

Environment:
Node: 18.5.0
yarn: 1.22.19

When i'm doing a yarn install;yarn prepark here the error I get.

```
error TS5083: Cannot read file '/Users/gaetansenn/Development/dewib/librairies/test-module/playground/.nuxt/tsconfig.json'.

src/module.ts(3,45): error TS2792: Cannot find module '@nuxt/kit'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?
src/module.ts(19,61): error TS1343: The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'es2022', 'esnext', 'system', 'node16', or 'nodenext'.

Error: Failed to compile. Check the logs above.
    at error (file:///Users/gaetansenn/Development/dewib/librairies/test-module/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at throwPluginError (file:///Users/gaetansenn/Development/dewib/librairies/test-module/node_modules/rollup/dist/es/shared/rollup.js:21587:12)
    at Object.error (file:///Users/gaetansenn/Development/dewib/librairies/test-module/node_modules/rollup/dist/es/shared/rollup.js:22541:20)
    at Object.error (file:///Users/gaetansenn/Development/dewib/librairies/test-module/node_modules/rollup/dist/es/shared/rollup.js:21764:42)
    at Object.transform (file:///Users/gaetansenn/Development/dewib/librairies/test-module/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1616:26)
    at file:///Users/gaetansenn/Development/dewib/librairies/test-module/node_modules/rollup/dist/es/shared/rollup.js:22748:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  id: '/Users/gaetansenn/Development/dewib/librairies/test-module/src/module.ts',
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  plugin: 'dts',
  watchFiles: [
    '/Users/gaetansenn/Development/dewib/librairies/test-module/src/module.ts'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

look's like it's working from the exemple/ folder.

any idea ?

**Comment by danielroe** [comment]
I believe you need to run `yarn dev:prepare` first which creates the `tsconfig.json` file.

**Comment by gaetansenn** [comment]
Hi @danielroe,

You are right the main module extend the `tsconfig.ts` that is generated from the playground.
I'm was actually not using the playground. 
I added the `prepare` script to only do a `nuxi prepare` and changed the main `ts.config.json` to extend the `./.nuxt/tsconfig.json`

Thank you for your help :)
